version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=subtitles

  django:
    build:
      context: ./back_end
      dockerfile: Dockerfile
    command: gunicorn back_end.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./back_end:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/subtitles

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./front_end/build:/usr/share/nginx/html
      - ./nginx-config:/etc/nginx/conf.d
      - ./certbot-data:/etc/letsencrypt
      - ./certbot-logs:/var/log/letsencrypt
    depends_on:
      - django
    networks:
      - nginx_network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot-data:/etc/letsencrypt
      - ./certbot-logs:/var/log/letsencrypt
      - ./front_end/build:/usr/share/nginx/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --domain yourdomain.com --agree-tos --no-eff-email --staging
    environment:
      - CERTBOT_EMAIL=lazyp.spam@gmail.com
    networks:
      - nginx_network

  networks:
    nginx_network:
      driver: bridge