# Generated by Django 5.0 on 2024-01-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0003_alter_subtitles_options_subtitles_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitles',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
