# Generated by Django 5.0 on 2024-02-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0004_alter_subtitles_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitles',
            name='location',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
