# Generated by Django 5.0 on 2024-02-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0005_subtitles_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtitles',
            old_name='location',
            new_name='cover_image_location',
        ),
        migrations.AddField(
            model_name='subtitles',
            name='subtitle_location',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
