# Generated by Django 5.0 on 2024-04-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0006_rename_location_subtitles_cover_image_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtitles',
            old_name='subtitle_location',
            new_name='folder_name',
        ),
        migrations.AddField(
            model_name='subtitles',
            name='subtitle_file_name',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
