# Generated by Django 5.0 on 2024-05-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0008_subtitles_episode_count_subtitles_trailer_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitles',
            name='trailer_url',
        ),
        migrations.AddField(
            model_name='subtitles',
            name='download_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subtitles',
            name='cover_image_location',
            field=models.CharField(default='./cover_img/', max_length=255),
        ),
    ]
